# Generated by Django 4.2.4 on 2023-09-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('list_users', 'Просмотр списка пользователей'), ('block_users', 'Блокировка пользователя')], 'verbose_name': 'пользователь', 'verbose_name_plural': 'пользователи'},
        ),
    ]
