# Generated by Django 4.2.4 on 2023-08-29 15:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Краткое название рассылки')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала рассылки')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='Время отправки письма')),
                ('end_date', models.DateField(verbose_name='Дата окончания рассылки')),
                ('last_time', models.DateField(default=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала рассылки'), verbose_name='дата последней отправки')),
                ('period', models.CharField(choices=[('day', 'День'), ('week', 'Месяц'), ('month', 'Год')], max_length=5, verbose_name='Периодичность рассылки')),
                ('state', models.CharField(choices=[('completed', 'Завершена'), ('created', 'Создана'), ('launched', 'Запущена'), ('stopped', 'Остановлена')], default='created', max_length=10, verbose_name='Статус рассылки')),
                ('clients', models.ManyToManyField(to='client.client', verbose_name='клиенты рассылки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last', models.DateTimeField(auto_now=True, verbose_name='Время последней отправки')),
                ('status', models.BooleanField(verbose_name='Статус попытки')),
                ('response', models.TextField(verbose_name='Ответ почтового сервиса')),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Логи')),
            ],
            options={
                'verbose_name': 'Лог рассылки',
                'verbose_name_plural': 'Логи рассылки',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='Тема письма')),
                ('content', models.TextField(verbose_name='Содержание письма')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='mailing.mailing', verbose_name='Настройки')),
            ],
            options={
                'verbose_name': 'содержание рассылки',
                'verbose_name_plural': 'содержание рассылок',
            },
        ),
    ]
