# Generated by Django 4.2.4 on 2023-09-01 19:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='Тема письма')),
                ('content', models.TextField(verbose_name='Содержание письма')),
            ],
            options={
                'verbose_name': 'содержание рассылки',
                'verbose_name_plural': 'содержание рассылок',
            },
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last', models.DateTimeField(auto_now=True, verbose_name='Время последней отправки')),
                ('status', models.BooleanField(verbose_name='Статус попытки')),
                ('response', models.TextField(verbose_name='Ответ почтового сервиса')),
            ],
            options={
                'verbose_name': 'Лог рассылки',
                'verbose_name_plural': 'Логи рассылки',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Краткое название рассылки')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала рассылки')),
                ('time', models.TimeField(default=django.utils.timezone.now, verbose_name='Время отправки письма')),
                ('end_date', models.DateField(verbose_name='Дата окончания рассылки')),
                ('next_date', models.DateField(blank=True, null=True, verbose_name='дата следующей отправки')),
                ('period', models.CharField(choices=[('day', 'день'), ('week', 'неделя'), ('month', 'месяц')], max_length=5, verbose_name='Периодичность рассылки')),
                ('state', models.CharField(choices=[('completed', 'завершена'), ('created', 'создана'), ('launched', 'запущена'), ('stopped', 'остановлена')], default='created', max_length=10, verbose_name='Статус рассылки')),
                ('send_today', models.BooleanField(blank=True, default=False, null=True, verbose_name='отправка сегодня')),
                ('clients', models.ManyToManyField(to='client.client', verbose_name='клиенты рассылки')),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
    ]
