# Generated by Django 4.2.4 on 2023-09-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailing_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='статус активации'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='state',
            field=models.CharField(choices=[('completed', 'завершена'), ('created', 'создана'), ('launched', 'запущена'), ('stopped', 'остановлена'), ('disabled', 'отключена')], default='created', max_length=10, verbose_name='Статус рассылки'),
        ),
    ]
