# Generated by Django 4.2.4 on 2023-09-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailing_is_active_alter_mailing_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('stop_mailing', 'Приостановка действия рассылки'), ('disable_mailing', 'Отключение рассылки рассылки')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.AlterField(
            model_name='mailing',
            name='state',
            field=models.CharField(choices=[('completed', 'завершена'), ('created', 'создана'), ('launched', 'запущена'), ('stopped', 'остановлена')], default='created', max_length=10, verbose_name='Статус рассылки'),
        ),
    ]
