# Generated by Django 4.2.4 on 2023-09-04 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_mailing_options_alter_mailing_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('stop_mailing', 'Приостановка действия рассылки'), ('disable_mailing', 'Отключение рассылки')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
