# Generated by Django 4.2.4 on 2023-09-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='содержание')),
                ('image', models.ImageField(upload_to='', verbose_name='изображение')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='количество просмотров')),
                ('date_publish', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блоги',
            },
        ),
    ]
